# 强化学习

### agent&env

状态S作为agent的输入:当前的界面作为状态，木板位置，块位置……

agent做动作action:小木板如何移动

env给agent反馈r

**奖赏值r**

### 四个子要素
- 策略policy 会用决策选取动作
- 奖赏函数 reward fucntion 评价动作获得的回报
- 值函数 value fuction 对当前状态评估  值函数越大，智能体进入这个状态越有利。
- 环境模型

#### 策略
从状态到action的映射
确定性策略（贪婪策略）：选概率最大的动作
$a=\pi(S)$

随机策略：按照概率来，就是在试错
$\pi(a|s)=P[At=a|St=s]$

#### 奖赏函数
把环境中感知到的状态映射为奖赏值，表示该状态内在的可取程度
$r(s,a)=E[R_{t+1}|S_t=s,A_t=a]$
？？

#### 值函数
评价状态的好坏，值函数越大，智能体进入这个状态越有利。
$v_{\pi}(s)=E_{\pi}[R_{t+1}+\gamma R_{t+2}+\gamma^2 R_{t+3}+...|S_t=s]$
？？
值函数是对奖赏的预测

值函数可以改善策略，策略可以改善值函数

#### 环境模型
环境模型是对外界环境的内部运行机制的预测，可以预测下一个状态和奖赏值


### 强化学习的分类
- 基于值的强化学习 value based  可以隐式的学习策略，通过优化值函数来提高性能。
- 基于策略的强化学习 policy based   显式地建模策略，然后通过优化策略来提高性能 没有值函数。走完一个ep后，才能更新策略
- 基于演员-评论员的强化学习 actor-critic based  既有值函数，又有策略函数

- 基于环境模型是否存在
    - 无模型强化学习 model-free  无模型强化学习是指智能体不知道环境的运行机制，只能通过与环境交互来学习。显式学习策略/值函数
    - 有模型强化学习 model-based  有模型强化学习是指智能体知道环境的运行机制，可以通过环境模型来预测下一个状态和奖励值。可以没有值函数，也可以没有策略函数
### 强化学习的上限是人的能力
- 没有训练数据
- 延迟奖励
- 智能体获得自己能力的过程，其实是不断地试错探索（trial-and-error exploration）的过程。探索 （exploration）和利用（exploitation）是强化学习里面非常核心的问题。其中，探索指尝试一些新的动作， 这些新的动作有可能会使我们得到更多的奖励，也有可能使我们“一无所有”；利用指采取已知的可以获得最多奖励的动作，重复执行这个动作，因为我们知道这样做可以获得一定的奖励。因此，我们需要在探 索和利用之间进行权衡，总体趋势，探索变少，利用变多

### 学习和规划
环境未知只能学习

In [4]:
!set http_proxy=http://127.0.0.1:10809 & set https_proxy=http://127.0.0.1:10809

In [1]:
pip install gym==0.25.2

     -------------------------------------- 734.5/734.5 kB 1.1 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Created wheel for gym: filename=gym-0.25.2-py3-none-any.whl size=852308 sha256=22094cda26baa3cbaa1278e994a3ebc30c9b2f71420ce599d38c9d4e41dc011c
  Stored in directory: c:\users\mayu\appdata\local\pip\cache\wheels\3a\a8\81\4ba83fc99a5637e27f4e16da10f9e15ff61f77ce524d23a8d7
Successfully built gym
Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install pygame

  Obtaining dependency information for pygame from https://files.pythonhosted.org/packages/ab/c8/07a58a91feac1a8eddaa0be12d55c4738c1bc513d12e163b39dbe6d3bd31/pygame-2.5.1-cp37-cp37m-win_amd64.whl.metadata
   ---------------------------------------- 10.8/10.8 MB 5.0 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [8]:
import gym  # 导入 Gym 的 Python 接口环境包
env = gym.make('CartPole-v0')  # 构建实验环境
env.reset()  # 重置一个回合
for _ in range(200):
    env.render()  # 显示图形界面
    action = env.action_space.sample() # 从动作空间中随机选取一个动作
    observation, reward, done, info = env.step(action) # 用于提交动作，括号内是具体的动作
    print(observation)  # 打印出当前的四个观测值
env.close() # 关闭环境

[ 0.04435314 -0.15073483  0.00034596  0.32856548]
[0.04133844 0.0443822  0.00691727 0.03599167]
[ 0.04222609  0.23940428  0.00763711 -0.25450078]
[ 0.04701417  0.43441635  0.00254709 -0.5447651 ]
[ 0.0557025   0.6295024  -0.00834821 -0.8366444 ]
[ 0.06829255  0.43449548 -0.0250811  -0.54659855]
[ 0.07698246  0.62996066 -0.03601307 -0.8470772 ]
[ 0.08958167  0.8255549  -0.05295461 -1.1508639 ]
[ 0.10609277  1.0213263  -0.07597189 -1.4596708 ]
[ 0.1265193  0.8272138 -0.1051653 -1.1916561]
[ 0.14306358  1.0235292  -0.12899843 -1.5153638 ]
[ 0.16353415  0.83018273 -0.1593057  -1.2655743 ]
[ 0.18013781  1.0269407  -0.18461719 -1.6036122 ]
[ 0.20067662  1.2237049  -0.21668944 -1.9477125 ]
[ 0.22515072  1.0314487  -0.2556437  -1.7292817 ]
[ 0.2457797   1.22842    -0.29022932 -2.0894797 ]
[ 0.2703481  1.4250771 -0.3320189 -2.456263 ]
[ 0.29884964  1.6211754  -0.38114417 -2.8301759 ]
[ 0.33127314  1.4300337  -0.4377477  -2.673401  ]
[ 0.35987383  1.2399613  -0.4912157  -2.5398023 ]


c:\Users\MaYu\anaconda3\envs\joyrl\lib\site-packages\gym\envs\classic_control\cartpole.py:180: UserWarning: WARN: You are calling 'step()' even though this environment has already returned terminated = True. You should always call 'reset()' once you receive 'terminated = True' -- any further steps are undefined behavior.
  "You are calling 'step()' even though this "


[ 0.38467306  1.4349059  -0.54201174 -2.9363232 ]
[ 0.41337118  1.2454711  -0.6007382  -2.8445609 ]
[ 0.43828058  1.4383098  -0.65762943 -3.2493591 ]
[ 0.4670468  1.6288639 -0.7226166 -3.6552837]
[ 0.49962407  1.8164752  -0.7957223  -4.060805  ]
[ 0.5359536  2.0004056 -0.8769384 -4.4638925]
[ 0.57596165  2.1798716  -0.96621627 -4.86207   ]
[ 0.6195591  1.9822688 -1.0634576 -4.935475 ]
[ 0.6592045  1.7835724 -1.1621672 -5.047637 ]
[ 0.69487596  1.9508085  -1.2631199  -5.417108  ]
[ 0.7338921  1.746143  -1.3714621 -5.604329 ]
[ 0.768815   1.9029865 -1.4835486 -5.939094 ]
[ 0.8068747  1.690274  -1.6023306 -6.204173 ]
[ 0.8406802  1.8367058 -1.726414  -6.4911017]
[ 0.8774143  1.9788696 -1.856236  -6.748498 ]
[ 0.91699165  2.1181028  -1.9912059  -6.971794  ]
[ 0.95935374  1.8883568  -2.130642   -7.380844  ]
[ 0.99712086  2.0248218  -2.2782588  -7.5212555 ]
[ 1.0376173  2.164991  -2.4286838 -7.608054 ]
[ 1.0809171  1.9330976 -2.5808449 -8.063469 ]
[ 1.1195791  1.7025524 -2.7421143 -8.512682 

# 自己设计奖励函数或者决策网络有加分

In [16]:
import gym

class SimpleAgent:
    def __init__(self, env):
        pass
    
    def decide(self, observation): # 决策
        position, velocity = observation
        lb = min(-0.09 * (position + 0.25) ** 2 + 0.03,
                0.3 * (position + 0.9) ** 4 - 0.008)
        ub = -0.07 * (position + 0.38) ** 2 + 0.07
        if lb < velocity < ub:
            action = 2
        else:
            action = 0
        return action # 返回动作

    def learn(self, *args): # 学习
        pass

def play(env, agent, render=False, train=False):
        episode_reward = 0. # 记录回合总奖励，初始值为0
        observation = env.reset() # 重置游戏环境，开始新回合
        while True: # 不断循环，直到回合结束
            if render: # 判断是否显示
                env.render() # 显示图形界面
            action = agent.decide(observation)
            next_observation, reward, done, _ = env.step(action) # 执行动作
            episode_reward += reward # 收集回合奖励
            if train: # 判断是否训练智能体
                agent.learn(observation, action, reward, done) # 学习
            if done: # 回合结束，跳出循环
                break
            observation = next_observation
        return episode_reward # 返回回合总奖励
    

env = gym.make('MountainCar-v0')
print('观测空间 = {}'.format(env.observation_space))
print('动作空间 = {}'.format(env.action_space))
print('观测范围 = {} ~ {}'.format(env.observation_space.low,
        env.observation_space.high))
print('动作数 = {}'.format(env.action_space.n))
env.seed(666) # 设置随机种子，让结果可复现
agent = SimpleAgent(env)
episode_reward = play(env, agent, render=True)
print('回合奖励 = {}'.format(episode_reward))
env.close() # 关闭图形界面


观测空间 = Box([-1.2  -0.07], [0.6  0.07], (2,), float32)
动作空间 = Discrete(3)
观测范围 = [-1.2  -0.07] ~ [0.6  0.07]
动作数 = 3
回合奖励 = -91.0


# 参考链接
[RL](http://karpathy.github.io/2016/05/31/rl/)
[Play with OpenAl gym and the example code](https://github.com/cuhkrlcourse/RLexample)
[python tutorial](http://s23n.github.o/python-numpy-tutoriall)

[torch tutorial](https://pytorch.org/tutorials/beginner/deep learning_60min_blitzh.tml)
