# 强化学习

### agent&env
![](https://datawhalechina.github.io/easy-rl/img/ch1/1.1.png)
状态S作为agent（智能体）的输入:当前的界面作为状态，木板位置，块位置……

agent做动作action:小木板如何移动

env给agent反馈r

**奖赏值r**

### 四个子要素
- 策略policy 会用决策选取动作
- 奖赏函数 reward fucntion 评价动作获得的回报
- 值函数 value fuction 对当前状态评估  值函数越大，智能体进入这个状态越有利。
- 环境模型

#### 策略
从状态到action的映射
确定性策略（贪婪策略）：选概率最大的动作
$a=\pi(S)$

随机策略：按照概率来，就是在试错
$\pi(a|s)=P[At=a|St=s]$

#### 值函数
评价状态的好坏，值函数越大，智能体进入这个状态越有利。

$$
V_{\pi}(s) \doteq \mathbb{E}_{\pi}\left[G_{t} \mid s_{t}=s\right]=\mathbb{E}_{\pi}\left[\sum_{k=0}^{\infty} \gamma^{k} r_{t+k+1} \mid s_{t}=s\right], \text{对于所有的} s \in S
$$


$$
Q_{\pi}(s, a) \doteq \mathbb{E}_{\pi}\left[G_{t} \mid s_{t}=s, a_{t}=a\right]=\mathbb{E}_{\pi}\left[\sum_{k=0}^{\infty} \gamma^{k} r_{t+k+1} \mid s_{t}=s, a_{t}=a\right]
$$

值函数是对奖赏的预测

值函数可以改善策略，策略可以改善值函数

#### 奖赏函数
把环境中感知到的状态映射为奖赏值，表示该状态内在的可取程度
$$
p_{s s^{\prime}}^{a}=p\left(s_{t+1}=s^{\prime} \mid s_{t}=s, a_{t}=a\right)
$$

奖励函数是指我们在当前状态采取了某个动作，可以得到多大的奖励，即
$$
R(s,a)=\mathbb{E}\left[r_{t+1} \mid s_{t}=s, a_{t}=a\right]
$$



#### 环境模型
环境模型是对外界环境的内部运行机制的预测，可以预测下一个状态和奖赏值


### 强化学习的分类
- 基于值的强化学习 value based  可以隐式的学习策略，通过优化值函数来提高性能。
- 基于策略的强化学习 policy based   显式地建模策略，然后通过优化策略来提高性能 没有值函数。走完一个ep后，才能更新策略
- 基于演员-评论员的强化学习 actor-critic based  既有值函数，又有策略函数

- 基于环境模型是否存在
    - 无模型强化学习 model-free  无模型强化学习是指智能体不知道环境的运行机制，只能通过与环境交互来学习。显式学习策略/值函数
    - 有模型强化学习 model-based  有模型强化学习是指智能体知道环境的运行机制，可以通过环境模型来预测下一个状态和奖励值。可以没有值函数，也可以没有策略函数
### 强化学习的上限超过人的能力
- 没有训练数据
- 延迟奖励
- 时间关联的数据
- 智能体获得自己能力的过程，其实是不断地试错探索（trial-and-error exploration）的过程。探索 （exploration）和利用（exploitation）是强化学习里面非常核心的问题。其中，探索指尝试一些新的动作， 这些新的动作有可能会使我们得到更多的奖励，也有可能使我们“一无所有”；利用指采取已知的可以获得最多奖励的动作，重复执行这个动作，因为我们知道这样做可以获得一定的奖励。因此，我们需要在探 索和利用之间进行权衡，总体趋势，探索变少，利用变多

### 学习和规划
环境未知只能学习

In [4]:
!set http_proxy=http://127.0.0.1:10809 & set https_proxy=http://127.0.0.1:10809

In [1]:
pip install gym==0.25.2

     -------------------------------------- 734.5/734.5 kB 1.1 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Created wheel for gym: filename=gym-0.25.2-py3-none-any.whl size=852308 sha256=22094cda26baa3cbaa1278e994a3ebc30c9b2f71420ce599d38c9d4e41dc011c
  Stored in directory: c:\users\mayu\appdata\local\pip\cache\wheels\3a\a8\81\4ba83fc99a5637e27f4e16da10f9e15ff61f77ce524d23a8d7
Successfully built gym
Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install pygame

  Obtaining dependency information for pygame from https://files.pythonhosted.org/packages/ab/c8/07a58a91feac1a8eddaa0be12d55c4738c1bc513d12e163b39dbe6d3bd31/pygame-2.5.1-cp37-cp37m-win_amd64.whl.metadata
   ---------------------------------------- 10.8/10.8 MB 5.0 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [1]:
import gym  # 导入 Gym 的 Python 接口环境包
env = gym.make('CartPole-v0')  # 构建实验环境
env.reset()  # 重置一个回合
for _ in range(200):
    env.render()  # 显示图形界面
    action = env.action_space.sample() # 从动作空间中随机选取一个动作
    observation, reward, done, info = env.step(action) # 用于提交动作，括号内是具体的动作
    print(observation)  # 打印出当前的四个观测值
env.close() # 关闭环境

c:\Users\MaYu\anaconda3\envs\joyrl\lib\site-packages\gym\envs\registration.py:594: UserWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1`.
  f"The environment {id} is out of date. You should consider "
c:\Users\MaYu\anaconda3\envs\joyrl\lib\site-packages\gym\core.py:318: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  "Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future."
c:\Users\MaYu\anaconda3\envs\joyrl\lib\site-packages\gym\wrappers\step_api_compatibility.py:40: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. 

[ 0.03480404  0.21543217 -0.01452893 -0.28239387]
[ 0.03911269  0.02052044 -0.0201768   0.00567152]
[ 0.03952309  0.21592586 -0.02006337 -0.29330853]
[ 0.04384161  0.41132802 -0.02592954 -0.592251  ]
[ 0.05206817  0.6068032  -0.03777456 -0.89298767]
[ 0.06420424  0.80241656 -0.05563432 -1.1973015 ]
[ 0.08025257  0.6080571  -0.07958034 -0.92256135]
[ 0.09241371  0.41409528 -0.09803157 -0.6559114 ]
[ 0.10069562  0.6104354  -0.1111498  -0.9777828 ]
[ 0.11290433  0.80685806 -0.13070546 -1.3032093 ]


c:\Users\MaYu\anaconda3\envs\joyrl\lib\site-packages\gym\core.py:50: DeprecationWarning: WARN: You are calling render method, but you didn't specified the argument render_mode at environment initialization. To maintain backward compatibility, the environment will render in human mode.
If you want to render in human mode, initialize the environment in this way: gym.make('EnvName', render_mode='human') and don't call the render method.
See here for more information: https://www.gymlibrary.ml/content/api/
  "You are calling render method, "


[ 0.1290415   0.6136136  -0.15676965 -1.0541332 ]
[ 0.14131376  0.42087778 -0.1778523  -0.8144766 ]
[ 0.14973131  0.6179312  -0.19414183 -1.1574075 ]
[ 0.16208994  0.4257952  -0.21728998 -0.93133765]
[ 0.17060584  0.23416159 -0.23591675 -0.7140283 ]
[ 0.17528908  0.4316371  -0.25019732 -1.0707545 ]
[ 0.18392181  0.62903696 -0.2716124  -1.4304279 ]
[ 0.19650255  0.8262911  -0.30022097 -1.7943376 ]
[ 0.21302837  0.63551253 -0.3361077  -1.6079148 ]
[ 0.22573863  0.83269846 -0.36826602 -1.9841093 ]


c:\Users\MaYu\anaconda3\envs\joyrl\lib\site-packages\gym\envs\classic_control\cartpole.py:180: UserWarning: WARN: You are calling 'step()' even though this environment has already returned terminated = True. You should always call 'reset()' once you receive 'terminated = True' -- any further steps are undefined behavior.
  "You are calling 'step()' even though this "


[ 0.2423926  0.6428113 -0.4079482 -1.824215 ]
[ 0.2552488   0.45380083 -0.4444325  -1.6806031 ]
[ 0.26432484  0.65064263 -0.47804457 -2.0735865 ]
[ 0.2773377   0.84665734 -0.5195163  -2.4699006 ]
[ 0.29427084  0.6581607  -0.5689143  -2.3704205 ]
[ 0.30743405  0.85270727 -0.6163227  -2.7746575 ]
[ 0.3244882  0.6646071 -0.6718159 -2.7143636]
[ 0.33778033  0.4773069  -0.7261031  -2.6774538 ]
[ 0.3473265  0.6687308 -0.7796522 -3.0873692]
[ 0.36070108  0.48102954 -0.8413996  -3.0938327 ]
[ 0.3703217   0.66868216 -0.90327626 -3.5006154 ]
[ 0.38369533  0.8530658  -0.97328854 -3.9027224 ]
[ 0.40075666  1.0335467  -1.051343   -4.2980876 ]
[ 0.42142758  1.209501   -1.1373048  -4.6843233 ]
[ 0.4456176  1.3803658 -1.2309912 -5.058785 ]
[ 0.4732249  1.5457013 -1.3321669 -5.4186344]
[ 0.50413895  1.7052605  -1.4405396  -5.760876  ]
[ 0.5382441  1.8590617 -1.5557572 -6.082351 ]
[ 0.5754254  1.6438131 -1.6774042 -6.3714623]
[ 0.60830164  1.4237156  -1.8048334  -6.6989226 ]
[ 0.636776   1.5633473 -1.93

# 自己设计奖励函数或者决策网络有加分

In [2]:
import gym

class SimpleAgent:
    def __init__(self, env):
        pass
    
    def decide(self, observation): # 决策
        position, velocity = observation
        lb = min(-0.09 * (position + 0.25) ** 2 + 0.03,
                0.3 * (position + 0.9) ** 4 - 0.008)
        ub = -0.07 * (position + 0.38) ** 2 + 0.07
        if lb < velocity < ub:
            action = 2
        else:
            action = 0
        return action # 返回动作

    def learn(self, *args): # 学习
        pass

def play(env, agent, render=False, train=False):
        episode_reward = 0. # 记录回合总奖励，初始值为0
        observation = env.reset() # 重置游戏环境，开始新回合
        while True: # 不断循环，直到回合结束
            if render: # 判断是否显示
                env.render() # 显示图形界面
            action = agent.decide(observation)
            next_observation, reward, done, _ = env.step(action) # 执行动作
            episode_reward += reward # 收集回合奖励
            if train: # 判断是否训练智能体
                agent.learn(observation, action, reward, done) # 学习
            if done: # 回合结束，跳出循环
                break
            observation = next_observation
        return episode_reward # 返回回合总奖励
    

env = gym.make('MountainCar-v0')
print('观测空间 = {}'.format(env.observation_space))
print('动作空间 = {}'.format(env.action_space))
print('观测范围 = {} ~ {}'.format(env.observation_space.low,
        env.observation_space.high))
print('动作数 = {}'.format(env.action_space.n))
env.seed(666) # 设置随机种子，让结果可复现
agent = SimpleAgent(env)
episode_reward = play(env, agent, render=True)
print('回合奖励 = {}'.format(episode_reward))
env.close() # 关闭图形界面


c:\Users\MaYu\anaconda3\envs\joyrl\lib\site-packages\gym\core.py:318: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  "Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future."
c:\Users\MaYu\anaconda3\envs\joyrl\lib\site-packages\gym\wrappers\step_api_compatibility.py:40: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  "Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future."
c:\Users\MaYu\

观测空间 = Box([-1.2  -0.07], [0.6  0.07], (2,), float32)
动作空间 = Discrete(3)
观测范围 = [-1.2  -0.07] ~ [0.6  0.07]
动作数 = 3
回合奖励 = -91.0


# 参考链接
[RL](http://karpathy.github.io/2016/05/31/rl/)

[Play with OpenAl gym and the example code](https://github.com/cuhkrlcourse/RLexample)

[python tutorial](http://s23n.github.o/python-numpy-tutoriall)

[torch tutorial](https://pytorch.org/tutorials/beginner/deep_learning_60min_blitzh.tml)
